"""CADE-owned launch + handoff-resume for the terminal CLI agent.

CADE auto-starts a CLI coding agent (Claude Code by default) in the PTY. When
that agent exits in a TTY and the project has a freshly written handoff brief
(``docs/plans/handoff/<slug>.md``, from the /handoff skill), we relaunch the
agent in the same terminal seeded with a prompt telling it to read the brief and
resume — so closing a session with Ctrl-D rolls straight into the next one with
no copy-paste.

This used to live in a user ``~/.bashrc`` function (``claude-resume.sh``), which
silently died whenever the spawned shell wasn't an interactive bash that sourced
that file (packaged app, remote deploy, a shell swap, a Claude Code update).
Owning it here makes the behaviour shell-agnostic and agent-agnostic: the agent
command and how it takes a starting prompt come from the :class:`CliAgent`
descriptor, so pointing CADE at a different agent is a config change rather than
a rewrite.
"""

from __future__ import annotations

import shlex
import stat
from pathlib import Path
from typing import TYPE_CHECKING

from backend.hooks.wsl_path import get_wsl_cade_dir

if TYPE_CHECKING:
    from backend.config import CliAgent

# Seconds a brief may be older than and still trigger an auto-resume. Keeps a
# day-old handoff from ambushing a cold open; a manual `resume` ignores it.
DEFAULT_RESUME_WINDOW = 1800

SCRIPT_FILENAME = "cade-resume.sh"

# Path typed into the (possibly remote/WSL) shell. Logical, not resolved: the
# shell expands $HOME itself, so this works whether the PTY is local bash or a
# `wsl` session whose home differs from the Windows-side install path.
SHELL_SCRIPT_PATH = "$HOME/.cade/shell/" + SCRIPT_FILENAME


def render_resume_script(agent: "CliAgent", window: int = DEFAULT_RESUME_WINDOW) -> str:
    """Render the resume shell script with the agent descriptor baked in.

    Baked values act as defaults; matching ``CADE_*`` env vars override them at
    runtime, so a future per-tab agent selection needs no re-render.
    """
    return f"""\
# CADE handoff auto-resume — generated by CADE, do not edit.
#
# Relaunch the CLI agent into the freshest unresumed handoff brief when it exits
# in a TTY. The agent command and how it takes a starting prompt are filled in
# from CADE's cli_agent descriptor; env vars override the baked defaults.

__CADE_AGENT_CMD="${{CADE_CLI_AGENT:-{shlex.quote(agent.command)}}}"
__CADE_SEED_STYLE="${{CADE_CLI_AGENT_SEED_STYLE:-{shlex.quote(agent.seed_style)}}}"
__CADE_SEED_FLAG="${{CADE_CLI_AGENT_SEED_FLAG:-{shlex.quote(agent.seed_flag)}}}"
CADE_RESUME_WINDOW="${{CADE_RESUME_WINDOW:-{int(window)}}}"

# Per-project marker recording the last brief we auto-resumed. Keyed by a hash
# of the project path so it never pollutes the repo.
__cade_marker() {{
    local dir="$HOME/.cache/cade-resume"
    mkdir -p "$dir" 2>/dev/null
    printf '%s/%s' "$dir" "$(printf '%s' "$PWD" | cksum | cut -d' ' -f1)"
}}

# Newest handoff brief under the current dir (excluding a README index), or "".
__cade_latest_brief() {{
    find "$PWD/docs/plans/handoff" -maxdepth 1 -type f -name '*.md' ! -iname 'readme.md' \\
        -printf '%T@ %p\\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-
}}

# Echo a brief to auto-resume, or nothing. Applies the freshness + single-shot
# guards so this is silent in every project that isn't mid-handoff.
__cade_resume_brief() {{
    [ -d docs/plans/handoff ] || return 0
    local brief
    brief=$(__cade_latest_brief)
    [ -n "$brief" ] || return 0

    local now bmt
    now=$(date +%s)
    bmt=$(stat -c %Y "$brief" 2>/dev/null) || return 0
    [ $((now - bmt)) -le "$CADE_RESUME_WINDOW" ] || return 0   # too old -> ignore

    local marker mmt=0
    marker=$(__cade_marker)
    [ -f "$marker" ] && mmt=$(stat -c %Y "$marker" 2>/dev/null || echo 0)
    [ "$bmt" -gt "$mmt" ] || return 0                          # already resumed this brief

    printf '%s\\n' "$brief"
}}

# Run the agent once, applying the configured seed convention. "$1" is the
# starting prompt (empty -> plain launch). `command` reaches the real binary
# even if a same-named shell function exists.
__cade_agent() {{
    if [ -z "$1" ]; then
        command "$__CADE_AGENT_CMD"
    elif [ "$__CADE_SEED_STYLE" = "flag" ]; then
        command "$__CADE_AGENT_CMD" "$__CADE_SEED_FLAG" "$1"
    else
        command "$__CADE_AGENT_CMD" "$1"
    fi
}}

# Launch the agent, then keep relaunching into any fresh, unresumed handoff.
# Touching the marker BEFORE launching caps this at one relaunch per brief, so a
# crash-on-start or an immediate exit can't spin.
__cade_run() {{
    __cade_agent "$1"
    local code=$?
    [ -t 0 ] && [ -t 1 ] || return "$code"   # only resume real interactive TUIs
    local brief
    while brief=$(__cade_resume_brief); [ -n "$brief" ]; do
        touch "$(__cade_marker)"
        clear 2>/dev/null
        __cade_agent "Read $brief and resume the work it describes, following its Contract section."
    done
    return "$code"
}}

# Manual trigger: resume the latest handoff on demand (ignores the freshness
# window) — handy when you quit without a fresh brief and want back in.
resume() {{
    local brief
    brief=$(__cade_latest_brief)
    if [ -z "$brief" ]; then
        echo "No handoff brief found in docs/plans/handoff/." >&2
        return 1
    fi
    touch "$(__cade_marker)"
    clear 2>/dev/null
    __cade_agent "Read $brief and resume the work it describes, following its Contract section."
}}
"""


def resume_script_install_path() -> Path:
    """Resolved path the script is written to (UNC on Windows→WSL)."""
    return get_wsl_cade_dir() / "shell" / SCRIPT_FILENAME


def install_resume_script(
    agent: "CliAgent", window: int = DEFAULT_RESUME_WINDOW
) -> Path:
    """Write the rendered resume script to ~/.cade/shell/. Idempotent."""
    path = resume_script_install_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_resume_script(agent, window), encoding="utf-8")
    try:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    except OSError:
        # UNC paths from Windows can reject chmod; sourcing doesn't need +x.
        pass
    return path


def build_launch_command(initial_prompt: str | None, agent: "CliAgent") -> str:
    """The line typed into the PTY to start the agent with resume-on-exit.

    Sources the resume wrapper and hands off to ``__cade_run``. If sourcing
    fails (script missing/unreadable), falls back to launching the agent
    directly so a broken resume install can never leave a blank terminal.
    """
    seed = f" {shlex.quote(initial_prompt)}" if initial_prompt else ""
    direct = agent.direct_command(initial_prompt)
    return (
        f". {SHELL_SCRIPT_PATH} 2>/dev/null; "
        f"if command -v __cade_run >/dev/null 2>&1; then __cade_run{seed}; "
        f"else {direct}; fi"
    )
