"""CADE-owned launch + handoff-resume for the terminal CLI agent.

CADE auto-starts a CLI coding agent (Claude Code by default) in the PTY. When
that agent exits in a TTY and the project has a freshly written handoff brief
(``docs/plans/handoff/<slug>.md``, from the /handoff skill), we relaunch the
agent in the same terminal seeded with a prompt telling it to read the brief and
resume — so closing a session with Ctrl-D rolls straight into the next one with
no copy-paste.

This used to live in a user ``~/.bashrc`` function (``claude-resume.sh``), which
silently died whenever the spawned shell wasn't an interactive bash that sourced
that file (packaged app, remote deploy, a shell swap, a Claude Code update).
Owning it here makes the behaviour shell-agnostic and agent-agnostic: the agent
command and how it takes a starting prompt come from the :class:`CliAgent`
descriptor, so pointing CADE at a different agent is a config change rather than
a rewrite.
"""

from __future__ import annotations

import shlex
import stat
from pathlib import Path
from typing import TYPE_CHECKING

from backend.hooks.wsl_path import get_wsl_cade_dir

if TYPE_CHECKING:
    from backend.config import CliAgent

from backend.terminal.cli_agent_adapters import adapter_from_descriptor

# Seconds a brief may be older than and still trigger an auto-resume. Keeps a
# day-old handoff from ambushing a cold open; a manual `resume` ignores it.
DEFAULT_RESUME_WINDOW = 1800

SCRIPT_FILENAME = "cade-resume.sh"

# Path typed into the (possibly remote/WSL) shell. Logical, not resolved: the
# shell expands $HOME itself, so this works whether the PTY is local bash or a
# `wsl` session whose home differs from the Windows-side install path.
SHELL_SCRIPT_PATH = "$HOME/.cade/shell/" + SCRIPT_FILENAME


def render_resume_script(agent: "CliAgent", window: int = DEFAULT_RESUME_WINDOW) -> str:
    """Render the resume shell script with the agent descriptor baked in.

    Baked values act as defaults; matching ``CADE_*`` env vars override them at
    runtime, so a future per-tab agent selection needs no re-render.
    """
    adapter = adapter_from_descriptor(agent)
    mcp_array_assignment = adapter.shell_mcp_array_assignment()
    return f"""\
# CADE handoff auto-resume — generated by CADE, do not edit.
#
# Relaunch the CLI agent into the freshest unresumed handoff brief when it exits
# in a TTY. The agent command and how it takes a starting prompt are filled in
# from CADE's cli_agent descriptor; env vars override the baked defaults.

__CADE_AGENT_CMD="${{CADE_CLI_AGENT:-{shlex.quote(agent.command)}}}"
__CADE_SEED_STYLE="${{CADE_CLI_AGENT_SEED_STYLE:-{shlex.quote(agent.seed_style)}}}"
__CADE_SEED_FLAG="${{CADE_CLI_AGENT_SEED_FLAG:-{shlex.quote(agent.seed_flag)}}}"
__CADE_AGENT_ADAPTER="{adapter.id}"
CADE_RESUME_WINDOW="${{CADE_RESUME_WINDOW:-{int(window)}}}"

# Stable per-tab id CADE injects into the PTY env. Empty in a plain shell, in
# which case ownership tracking is off and the ambiguity guard below applies.
__cade_session_id() {{ printf '%s' "${{CADE_SESSION_ID:-}}"; }}

# Single-shot marker recording the last brief we auto-resumed. Keyed by the
# CADE session id when present so sibling tabs in one project don't share a
# marker; falls back to a hash of the project path for plain shells.
__cade_marker() {{
    local dir="$HOME/.cache/cade-resume" key
    mkdir -p "$dir" 2>/dev/null
    key=$(__cade_session_id)
    [ -n "$key" ] || key=$(printf '%s' "$PWD" | cksum | cut -d' ' -f1)
    printf '%s/%s' "$dir" "$key"
}}

# Newest handoff brief under the current dir (excluding a README index), or "".
__cade_latest_brief() {{
    find "$PWD/docs/plans/handoff" -maxdepth 1 -type f -name '*.md' ! -iname 'readme.md' \\
        -printf '%T@ %p\\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2-
}}

# The brief THIS tab wrote, recorded by CADE's edit hook in
# ~/.cache/cade-resume/owned-<session>. Echoed only when it still exists and
# lives under the current project's handoff dir (so a stale record from another
# project can't leak in). Empty when ownership is unknown.
__cade_owned_brief() {{
    local sid owned path
    sid=$(__cade_session_id)
    [ -n "$sid" ] || return 0
    owned="$HOME/.cache/cade-resume/owned-$sid"
    [ -f "$owned" ] || return 0
    path=$(cat "$owned" 2>/dev/null)
    [ -n "$path" ] && [ -f "$path" ] || return 0
    case "$path" in
        "$PWD/docs/plans/handoff/"*) printf '%s\\n' "$path" ;;
    esac
}}

# Handoff briefs under the current dir whose mtime is within the resume window,
# newest first, one path per line. Drives the ambiguity guard for plain shells.
__cade_fresh_briefs() {{
    local now line ts path
    now=$(date +%s)
    find "$PWD/docs/plans/handoff" -maxdepth 1 -type f -name '*.md' ! -iname 'readme.md' \\
        -printf '%T@ %p\\n' 2>/dev/null | sort -rn | while IFS= read -r line; do
        ts=${{line%% *}}; ts=${{ts%.*}}
        path=${{line#* }}
        [ $((now - ts)) -le "$CADE_RESUME_WINDOW" ] && printf '%s\\n' "$path"
    done
}}

# Print a one-time hint listing fresh briefs as `resume <slug>` lines so the
# user can pick deliberately instead of CADE adopting the wrong tab's handoff.
__cade_handoff_chooser() {{
    printf 'CADE: multiple fresh handoffs here — pick one with `resume <slug>`:\\n'
    local p slug
    while IFS= read -r p; do
        [ -n "$p" ] || continue
        slug=${{p##*/}}; printf '  resume %s\\n' "${{slug%.md}}"
    done
}}

# Echo a brief to auto-resume, or nothing. Prefers the brief this tab wrote
# (ownership). When ownership is tracked (CADE session) a tab NEVER adopts an
# unowned brief — those belong to other tabs — it just hints. In a plain shell
# where ownership is impossible, it resumes a lone fresh brief but refuses to
# guess between several. Applies the freshness + single-shot guards either way.
__cade_resume_brief() {{
    [ -d docs/plans/handoff ] || return 0

    local brief now sid bmt
    now=$(date +%s)
    sid=$(__cade_session_id)
    brief=$(__cade_owned_brief)

    if [ -z "$brief" ]; then
        local fresh
        fresh=$(__cade_fresh_briefs)
        [ -n "$fresh" ] || return 0
        if [ -n "$sid" ] || [ "$(printf '%s\\n' "$fresh" | grep -c .)" -gt 1 ]; then
            # CADE tab with no brief of its own (the fresh ones are other tabs'),
            # or a plain shell facing several fresh briefs: don't guess — hint.
            printf '%s\\n' "$fresh" | __cade_handoff_chooser >&2
            return 0
        fi
        brief=$fresh
    fi

    bmt=$(stat -c %Y "$brief" 2>/dev/null) || return 0
    [ $((now - bmt)) -le "$CADE_RESUME_WINDOW" ] || return 0   # too old -> ignore

    local marker mmt=0
    marker=$(__cade_marker)
    [ -f "$marker" ] && mmt=$(stat -c %Y "$marker" 2>/dev/null || echo 0)
    [ "$bmt" -gt "$mmt" ] || return 0                          # already resumed this brief

    printf '%s\\n' "$brief"
}}

# Patch MCP configs written by old packaged binaries: the PyInstaller extraction
# dir has no .py source files, so the generated script path doesn't exist.
# Replace with the venv Python + source scripts when available.
__cade_patch_mcp_config() {{
    [ -n "${{CADE_CLI_MCP_CONFIG:-}}" ] && [ -f "$CADE_CLI_MCP_CONFIG" ] || return 0
    python3 -c "
import json, sys, os
path = sys.argv[1]
try:
    cfg = json.load(open(path))
    changed = False
    for name, srv in cfg.get('mcpServers', {{}}).items():
        args = srv.get('args', [])
        if not (args and args[0].endswith('mcp_server.py') and not os.path.exists(args[0])):
            continue
        binary = srv.get('command', '')
        d = os.path.dirname(binary)
        candidates = [os.path.expanduser('~/.local/share/cade/.venv/bin/python')]
        for _ in range(6):
            candidates.insert(0, os.path.join(d, '.venv', 'bin', 'python'))
            d = os.path.dirname(d)
        for candidate in candidates:
            if os.path.exists(candidate):
                base = os.path.dirname(os.path.dirname(os.path.dirname(candidate)))
                suffix = '/backend/permissions/mcp_server.py' if 'permissions' in name else '/backend/orchestrator/mcp_server.py'
                script = base + suffix
                if os.path.exists(script):
                    srv['command'] = candidate
                    srv['args'] = [script]
                    changed = True
                break
    if changed:
        json.dump(cfg, open(path, 'w'), indent=2)
        os.chmod(path, 0o600)
except Exception:
    pass
" "$CADE_CLI_MCP_CONFIG" 2>/dev/null
}}

# Run the agent once, applying the configured seed convention. "$1" is the
# starting prompt (empty -> plain launch). `command` reaches the real binary
# even if a same-named shell function exists. An array carries the optional
# --mcp-config so a config path with spaces survives word splitting.
__cade_agent() {{
    local -a mcp=()
    if [ -n "${{CADE_CLI_MCP_CONFIG:-}}" ] && [ -f "$CADE_CLI_MCP_CONFIG" ]; then
        __cade_patch_mcp_config
        {mcp_array_assignment}
    fi
    if [ -z "$1" ]; then
        command "$__CADE_AGENT_CMD" "${{mcp[@]}}"
    elif [ "$__CADE_SEED_STYLE" = "flag" ]; then
        command "$__CADE_AGENT_CMD" "${{mcp[@]}}" "$__CADE_SEED_FLAG" "$1"
    else
        # `--` terminates the variadic --mcp-config so a positional prompt is not
        # swallowed as a second config path (Claude Code 2.x). Drop it and a
        # seeded resume dies with "MCP config file not found: <cwd>/<prompt>".
        command "$__CADE_AGENT_CMD" "${{mcp[@]}}" -- "$1"
    fi
}}

# Launch the agent, then keep relaunching into any fresh, unresumed handoff.
# Touching the marker BEFORE launching caps this at one relaunch per brief, so a
# crash-on-start or an immediate exit can't spin.
__cade_run() {{
    __cade_agent "$1"
    local code=$?
    [ -t 0 ] && [ -t 1 ] || return "$code"   # only resume real interactive TUIs
    local brief
    while brief=$(__cade_resume_brief); [ -n "$brief" ]; do
        touch "$(__cade_marker)"
        clear 2>/dev/null
        __cade_agent "Read $brief and resume the work it describes, following its Contract section."
    done
    return "$code"
}}

# Manual trigger (ignores the freshness window):
#   resume          -> this tab's own brief, else the newest in the project
#   resume <slug>   -> docs/plans/handoff/<slug>.md explicitly
# Handy when you quit without a fresh brief, or to pick among parallel streams.
resume() {{
    local brief
    if [ -n "$1" ]; then
        brief="$PWD/docs/plans/handoff/${{1%.md}}.md"
        if [ ! -f "$brief" ]; then
            echo "No handoff brief: $brief" >&2
            return 1
        fi
    else
        brief=$(__cade_owned_brief)
        [ -n "$brief" ] || brief=$(__cade_latest_brief)
    fi
    if [ -z "$brief" ]; then
        echo "No handoff brief found in docs/plans/handoff/." >&2
        return 1
    fi
    touch "$(__cade_marker)"
    clear 2>/dev/null
    __cade_agent "Read $brief and resume the work it describes, following its Contract section."
}}
"""


def resume_script_install_path() -> Path:
    """Resolved path the script is written to (UNC on Windows→WSL)."""
    return get_wsl_cade_dir() / "shell" / SCRIPT_FILENAME


def install_resume_script(
    agent: "CliAgent", window: int = DEFAULT_RESUME_WINDOW
) -> Path:
    """Write the rendered resume script to ~/.cade/shell/. Idempotent."""
    path = resume_script_install_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_resume_script(agent, window), encoding="utf-8")
    try:
        path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)
    except OSError:
        # UNC paths from Windows can reject chmod; sourcing doesn't need +x.
        pass
    return path


def build_launch_command(
    initial_prompt: str | None,
    agent: "CliAgent",
    mcp_config_path: str | Path | None = None,
) -> str:
    """The line typed into the PTY to start the agent with resume-on-exit.

    Sources the resume wrapper and hands off to ``__cade_run``. If sourcing
    fails (script missing/unreadable), falls back to launching the agent
    directly so a broken resume install can never leave a blank terminal.
    """
    adapter = adapter_from_descriptor(agent)
    seed = f" {shlex.quote(initial_prompt)}" if initial_prompt else ""
    direct = adapter.direct_command(initial_prompt, mcp_config_path)
    return (
        f". {SHELL_SCRIPT_PATH} 2>/dev/null; "
        f"if command -v __cade_run >/dev/null 2>&1; then __cade_run{seed}; "
        f"else {direct}; fi"
    )
