"""Command builders for CADE hooks.

Generates a self-contained Python script that runs inside Claude Code's
hook system, plus the settings.json command that invokes it.
"""

from __future__ import annotations

from backend.hooks.config import CADEHookOptions

# The hook script is a complete, standalone Python program (stdlib only,
# Python 3.8+) that Claude Code pipes hook JSON into via stdin.
#
# Placeholders replaced at generation time:
#   {filter_mode} — "plans_only" or "all_files"
HOOK_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""CADE hook script — sends edited files to the CADE viewer.

Generated by `python -m backend.main setup-hook`.
Do not edit manually; re-run setup-hook to regenerate.
"""

import fnmatch
import json
import os
import sys
import time
import urllib.request
import urllib.error

FILTER_MODE = "{filter_mode}"
DEFAULT_PORT = 3001
LOG_MAX_BYTES = 512 * 1024  # 512 KB
PROJECT_FILTER_FILENAME = os.path.join(".cade", "hook-filters.json")

cade_dir = os.path.join(os.path.expanduser("~"), ".cade")


def log(msg):
    """Append a timestamped line to ~/.cade/hook.log with size truncation."""
    log_path = os.path.join(cade_dir, "hook.log")
    try:
        if os.path.exists(log_path) and os.path.getsize(log_path) > LOG_MAX_BYTES:
            os.remove(log_path)
        with open(log_path, "a") as f:
            f.write("[%s] %s\\n" % (time.strftime("%Y-%m-%d %H:%M:%S"), msg))
    except Exception:
        pass


def read_port():
    """Read port from ~/.cade/port, fall back to default."""
    port_file = os.path.join(cade_dir, "port")
    try:
        with open(port_file) as f:
            return int(f.read().strip())
    except Exception:
        return DEFAULT_PORT


def read_host():
    """Resolve the CADE server host via 3-tier strategy.

    1. Read ~/.cade/host (server-written, preferred)
    2. If in WSL: extract gateway IP from /proc/net/route
    3. Otherwise: localhost
    """
    host_file = os.path.join(cade_dir, "host")
    try:
        with open(host_file) as f:
            host = f.read().strip()
            if host:
                return host
    except Exception:
        pass

    # Detect WSL via /proc/version
    try:
        with open("/proc/version") as f:
            if "microsoft" in f.read().lower():
                return _wsl_gateway_ip() or "localhost"
    except Exception:
        pass

    return "localhost"


def _wsl_gateway_ip():
    """Extract the default gateway IP from /proc/net/route.

    The default route has destination 00000000. The gateway field
    is a little-endian hex-encoded IPv4 address.
    """
    try:
        with open("/proc/net/route") as f:
            for line in f:
                fields = line.strip().split()
                if len(fields) >= 3 and fields[1] == "00000000":
                    hex_ip = fields[2]
                    # Little-endian hex to dotted-quad
                    ip_bytes = [int(hex_ip[i:i+2], 16) for i in range(0, 8, 2)]
                    return "%d.%d.%d.%d" % tuple(ip_bytes)
    except Exception:
        pass
    return None


def find_project_root(start_dir):
    """Walk up from start_dir looking for a directory containing .cade/.

    Returns the project root path (containing .cade/) or None if not found.
    Stops at filesystem root.
    """
    if not start_dir:
        return None
    current = os.path.abspath(start_dir)
    while True:
        if os.path.isdir(os.path.join(current, ".cade")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return None
        current = parent


def read_project_filters(project_root):
    """Read filters from <project_root>/.cade/hook-filters.json.

    Expected shape: {"include": ["plans/*.md"], "exclude": ["*.lock"]}
    Returns {"include": [...], "exclude": [...]} or None if not present.
    """
    if not project_root:
        return None
    filters_path = os.path.join(project_root, PROJECT_FILTER_FILENAME)
    if not os.path.isfile(filters_path):
        return None
    try:
        with open(filters_path) as f:
            data = json.load(f)
        result = {}
        include = data.get("include")
        if isinstance(include, list) and all(isinstance(p, str) for p in include):
            result["include"] = include
        exclude = data.get("exclude")
        if isinstance(exclude, list) and all(isinstance(p, str) for p in exclude):
            result["exclude"] = exclude
        return result if result else None
    except Exception as e:
        log("Failed to read project filters %s: %s" % (filters_path, e))
    return None


def matches_project_filters(file_path, project_root, patterns):
    """Match file_path (absolute) against project-relative globs.

    Patterns are fnmatch-style ('*' matches anything including '/').
    """
    try:
        rel = os.path.relpath(file_path, project_root)
    except ValueError:
        return False
    return any(fnmatch.fnmatch(rel, pat) for pat in patterns)


def matches_filter(file_path, cwd):
    """Return True if the file should be sent to the CADE viewer.

    Filter layers applied in order:
      1. Exclude patterns in hook-filters.json block the file (highest priority).
      2. Global FILTER_MODE — 'plans_only' matches plans/*.md; 'all_files' passes all.
      3. Per-project include globs add extra files on top of the global mode.
    """
    project_root = find_project_root(cwd)
    project_filters = read_project_filters(project_root)

    # Exclude patterns override everything — if matched, never send to viewer
    if project_filters and project_root:
        exclude = project_filters.get("exclude", [])
        if exclude and matches_project_filters(file_path, project_root, exclude):
            return False

    if FILTER_MODE == "all_files":
        return True

    # Global plans default — applies in every project
    if "plans/" in file_path and file_path.endswith(".md"):
        return True

    # Project-specific include additions
    if project_filters and project_root:
        include = project_filters.get("include", [])
        if include and matches_project_filters(file_path, project_root, include):
            return True

    return False


def main():
    try:
        data = json.load(sys.stdin)
    except Exception as e:
        log("Failed to parse stdin JSON: %s" % e)
        return

    file_path = ""
    try:
        file_path = data["tool_input"]["file_path"]
    except (KeyError, TypeError):
        # tool_response may not contain file_path (e.g. on error)
        log("No file_path in hook data")
        return

    session_id = data.get("session_id", "")
    cwd = data.get("cwd", "")

    if not matches_filter(file_path, cwd):
        return

    host = read_host()
    port = read_port()
    url = "http://%s:%d/api/view" % (host, port)

    payload = json.dumps({
        "path": file_path,
        "session_id": session_id or None,
        "cwd": cwd or None,
    }).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=3) as resp:
            log("POST %s -> %d (%s)" % (url, resp.status, file_path))
    except Exception as e:
        log("POST %s failed: %s (%s)" % (url, e, file_path))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        try:
            log("Unhandled error: %s" % e)
        except Exception:
            pass
    # Always exit 0 so we never block Claude Code
    sys.exit(0)
'''


def generate_hook_script(options: CADEHookOptions) -> str:
    """Render the hook script template with the given options.

    Uses str.replace() instead of str.format() to avoid conflicts
    with JSON dict literals in the template.

    Args:
        options: Hook configuration options.

    Returns:
        Complete Python script source as a string.
    """
    filter_mode = "all_files" if options.all_files else "plans_only"
    return HOOK_SCRIPT_TEMPLATE.replace("{filter_mode}", filter_mode)


def build_hook_command() -> str:
    """Build the shell command that settings.json will execute.

    Returns:
        Command string invoking the installed hook script.
    """
    return "python3 ~/.cade/hooks/view_file.py"


def build_hook_config(options: CADEHookOptions) -> dict:
    """Build the complete hook configuration dict.

    Args:
        options: Hook configuration options.

    Returns:
        Dict suitable for adding to settings.json hooks.
    """
    return {
        "matcher": "Edit|Write",
        "hooks": [
            {
                "type": "command",
                "command": build_hook_command(),
            }
        ],
    }
