"""Command builders for CADE hooks.

Generates a self-contained Python script that runs inside Claude Code's
hook system, plus the settings.json command that invokes it.
"""

from __future__ import annotations

from backend.hooks.config import CADEHookOptions

# The hook script is a complete, standalone Python program (stdlib only,
# Python 3.8+) that Claude Code pipes hook JSON into via stdin.
#
# Placeholders replaced at generation time:
#   {filter_mode} — "plans_only" or "all_files"
HOOK_SCRIPT_TEMPLATE = '''\
#!/usr/bin/env python3
"""CADE hook script — sends edited files to the CADE viewer.

Generated by `python -m backend.main setup-hook`.
Do not edit manually; re-run setup-hook to regenerate.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

FILTER_MODE = "{filter_mode}"
DEFAULT_PORT = 3001
LOG_MAX_BYTES = 512 * 1024  # 512 KB

cade_dir = os.path.join(os.path.expanduser("~"), ".cade")


def log(msg):
    """Append a timestamped line to ~/.cade/hook.log with size truncation."""
    log_path = os.path.join(cade_dir, "hook.log")
    try:
        if os.path.exists(log_path) and os.path.getsize(log_path) > LOG_MAX_BYTES:
            os.remove(log_path)
        with open(log_path, "a") as f:
            f.write("[%s] %s\\n" % (time.strftime("%Y-%m-%d %H:%M:%S"), msg))
    except Exception:
        pass


def read_port():
    """Read port from ~/.cade/port, fall back to default."""
    port_file = os.path.join(cade_dir, "port")
    try:
        with open(port_file) as f:
            return int(f.read().strip())
    except Exception:
        return DEFAULT_PORT


def read_host():
    """Resolve the CADE server host via 3-tier strategy.

    1. Read ~/.cade/host (server-written, preferred)
    2. If in WSL: extract gateway IP from /proc/net/route
    3. Otherwise: localhost
    """
    host_file = os.path.join(cade_dir, "host")
    try:
        with open(host_file) as f:
            host = f.read().strip()
            if host:
                return host
    except Exception:
        pass

    # Detect WSL via /proc/version
    try:
        with open("/proc/version") as f:
            if "microsoft" in f.read().lower():
                return _wsl_gateway_ip() or "localhost"
    except Exception:
        pass

    return "localhost"


def _wsl_gateway_ip():
    """Extract the default gateway IP from /proc/net/route.

    The default route has destination 00000000. The gateway field
    is a little-endian hex-encoded IPv4 address.
    """
    try:
        with open("/proc/net/route") as f:
            for line in f:
                fields = line.strip().split()
                if len(fields) >= 3 and fields[1] == "00000000":
                    hex_ip = fields[2]
                    # Little-endian hex to dotted-quad
                    ip_bytes = [int(hex_ip[i:i+2], 16) for i in range(0, 8, 2)]
                    return "%d.%d.%d.%d" % tuple(ip_bytes)
    except Exception:
        pass
    return None


def matches_filter(file_path):
    """Return True if the file passes the configured filter."""
    if FILTER_MODE == "all_files":
        return True
    # plans_only: match plans/*.md anywhere in path
    return "plans/" in file_path and file_path.endswith(".md")


def main():
    try:
        data = json.load(sys.stdin)
    except Exception as e:
        log("Failed to parse stdin JSON: %s" % e)
        return

    file_path = ""
    try:
        file_path = data["tool_input"]["file_path"]
    except (KeyError, TypeError):
        # tool_response may not contain file_path (e.g. on error)
        log("No file_path in hook data")
        return

    if not matches_filter(file_path):
        return

    session_id = data.get("session_id", "")
    cwd = data.get("cwd", "")

    host = read_host()
    port = read_port()
    url = "http://%s:%d/api/view" % (host, port)

    payload = json.dumps({
        "path": file_path,
        "session_id": session_id or None,
        "cwd": cwd or None,
    }).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=3) as resp:
            log("POST %s -> %d (%s)" % (url, resp.status, file_path))
    except Exception as e:
        log("POST %s failed: %s (%s)" % (url, e, file_path))


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        try:
            log("Unhandled error: %s" % e)
        except Exception:
            pass
    # Always exit 0 so we never block Claude Code
    sys.exit(0)
'''


def generate_hook_script(options: CADEHookOptions) -> str:
    """Render the hook script template with the given options.

    Uses str.replace() instead of str.format() to avoid conflicts
    with JSON dict literals in the template.

    Args:
        options: Hook configuration options.

    Returns:
        Complete Python script source as a string.
    """
    filter_mode = "all_files" if options.all_files else "plans_only"
    return HOOK_SCRIPT_TEMPLATE.replace("{filter_mode}", filter_mode)


def build_hook_command() -> str:
    """Build the shell command that settings.json will execute.

    Returns:
        Command string invoking the installed hook script.
    """
    return "python3 ~/.cade/hooks/view_file.py"


def build_hook_config(options: CADEHookOptions) -> dict:
    """Build the complete hook configuration dict.

    Args:
        options: Hook configuration options.

    Returns:
        Dict suitable for adding to settings.json hooks.
    """
    return {
        "matcher": "Edit|Write",
        "hooks": [
            {
                "type": "command",
                "command": build_hook_command(),
            }
        ],
    }
